services:
  kinopoisk-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: movies-app
    ports:
      - "${APP_CONFIG__RUN__PORT}:8000"
    command: "uvicorn main:main_app --reload --host 0.0.0.0 --port 8000"
    env_file:
      - ../.env
    volumes:
      - ../app/:/app/
    networks:
      - backend

networks:
  backend:
    driver: bridge