services:
  kinopoisk-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: kinopoisk-app
    ports:
      - "8000:8000"
    command: "uvicorn main:main_app --reload --host 0.0.0.0 --port 8000"
    volumes:
      - ../app/:/app/
    networks:
      - backend

networks:
  backend:
    driver: bridge